# Generated by Django 6.0.5 on 2026-06-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionMasterPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=120)),
                ('plan_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refundable', models.BooleanField(default=False)),
                ('non_refundable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_master_plans',
                'ordering': ['plan_price', 'plan_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('nominee_full_name', models.CharField(blank=True, max_length=150)),
                ('nominee_relationship', models.CharField(blank=True, max_length=80)),
                ('nominee_phone_number', models.CharField(blank=True, max_length=20)),
                ('how_did_you_hear_about_club', models.CharField(blank=True, max_length=150)),
                ('membership_table_id', models.TextField(blank=True)),
                ('payment_details', models.TextField(blank=True)),
                ('uploaded_form_document', models.ImageField(blank=True, null=True, upload_to='user_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='web.subscriptionmasterplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
