# Generated by Django 6.0.5 on 2026-06-03 10:34

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_demo_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SubscriptionMasterPlan = apps.get_model('web', 'SubscriptionMasterPlan')
    UserProfile = apps.get_model('web', 'UserProfile')

    plan, _ = SubscriptionMasterPlan.objects.get_or_create(
        plan_name='Demo Membership Plan',
        defaults={
            'plan_price': '9999.00',
            'refundable': True,
            'non_refundable': False,
        },
    )

    user, _ = User.objects.update_or_create(
        username='demo_user',
        defaults={
            'password': make_password('Demo@123'),
            'email': 'demo.user@sfc.local',
            'first_name': 'Demo',
            'last_name': 'User',
            'is_active': True,
            'is_staff': False,
            'is_superuser': False,
        },
    )

    UserProfile.objects.update_or_create(
        user=user,
        defaults={
            'full_name': 'Demo User',
            'dob': '1995-01-01',
            'pan_no': 'ABCDE1234F',
            'gender': 'O',
            'nationality': 'Indian',
            'address': 'Demo Address, SFC Club Area',
            'city': 'Kolkata',
            'state': 'West Bengal',
            'postal_code': '700001',
            'phone_number': '9999999999',
            'email_address': 'demo.user@sfc.local',
            'nominee_full_name': 'Demo Nominee',
            'nominee_relationship': 'Family',
            'nominee_phone_number': '8888888888',
            'how_did_you_hear_about_club': 'Website',
            'membership_table_id': 'SFC-DEMO-0001',
            'payment_details': 'Amount: Rs. 9999.00; Method: Cash; Paid by: Demo User',
            'subscription_plan': plan,
            'is_active': True,
            'ip_address': '127.0.0.1',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_demo_data, migrations.RunPython.noop),
    ]
