# Generated by Django 6.0.5 on 2026-06-03 10:45

from django.db import migrations, models
from django.utils import timezone


def assign_generated_profile_ids(apps, schema_editor):
    UserProfile = apps.get_model('web', 'UserProfile')
    year = timezone.localdate().year
    prefix = f'SFC-{year}-'

    for index, profile in enumerate(UserProfile.objects.order_by('created_at', 'user_id'), start=1):
        generated_id = f'{prefix}{index:04d}'
        UserProfile.objects.filter(pk=profile.pk).update(id=generated_id)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='membership_table_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.RunPython(assign_generated_profile_ids, migrations.RunPython.noop),
    ]
