# Generated by Django 6.0.5 on 2026-06-03 11:01

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def seed_admin_account(apps, schema_editor):
    AdminAccount = apps.get_model('web', 'AdminAccount')
    AdminAccount.objects.update_or_create(
        username='admin',
        defaults={
            'password': make_password('Admin@123'),
            'name': 'Super Admin',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_use_generated_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_table',
                'ordering': ['username'],
            },
        ),
        migrations.RunPython(seed_admin_account, migrations.RunPython.noop),
    ]
