# Generated by Django 6.0.5 on 2026-06-03 11:38

import django.db.models.deletion
from django.db import migrations, models


def seed_subscription_statuses(apps, schema_editor):
    SubscriptionStatusMaster = apps.get_model('web', 'SubscriptionStatusMaster')
    UserProfile = apps.get_model('web', 'UserProfile')
    statuses = ['pending', 'completed', 'rejected', 'transfered', 'closed']

    for status_name in statuses:
        SubscriptionStatusMaster.objects.get_or_create(status_name=status_name)

    pending_status = SubscriptionStatusMaster.objects.get(status_name='pending')
    UserProfile.objects.filter(subscription_status__isnull=True).update(
        subscription_status=pending_status,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_create_admin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionStatusMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_status_master',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='web.subscriptionstatusmaster'),
        ),
        migrations.RunPython(seed_subscription_statuses, migrations.RunPython.noop),
    ]
