# Generated by Django 6.0.5 on 2026-06-03 15:57

import django.db.models.deletion
from django.db import migrations, models


EVENT_RULE_SEEDS = [
    (
        'user_registered',
        'User Registration',
        'Created when a user signs up from the mobile app.',
        'Welcome to SuperFlow Food Club',
        'Hello {full_name}, your SFC account has been created. Your member ID is {member_id}.',
        'app://dashboard',
    ),
    (
        'subscription_selected',
        'Subscription Selected',
        'Created when a user chooses a subscription plan.',
        'Subscription Plan Selected',
        'Hello {full_name}, you selected {plan_name}. Please complete payment and submit the physical form.',
        'app://subscription',
    ),
    (
        'payment_pending',
        'Payment Pending',
        'Created when payment details are still pending.',
        'Payment Pending',
        'Hello {full_name}, payment for {plan_name} is pending. Please complete payment to continue.',
        'app://payments',
    ),
    (
        'payment_completed',
        'Payment Completed',
        'Created when payment is recorded as completed.',
        'Payment Completed',
        'Hello {full_name}, payment for {plan_name} has been recorded.',
        'app://payments',
    ),
    (
        'subscription_pending_review',
        'Subscription Pending Review',
        'Created when subscription is waiting for office review.',
        'Subscription Pending Review',
        'Hello {full_name}, your {plan_name} subscription is pending office review.',
        'app://subscription/status',
    ),
    (
        'subscription_approved',
        'Subscription Approved',
        'Created when admin approves a subscription.',
        'Subscription Approved',
        'Hello {full_name}, your {plan_name} subscription has been approved.',
        'app://subscription/status',
    ),
    (
        'subscription_rejected',
        'Subscription Rejected',
        'Created when admin rejects a subscription.',
        'Subscription Rejected',
        'Hello {full_name}, your {plan_name} subscription request has been rejected. Please contact the office for details.',
        'app://subscription/status',
    ),
    (
        'subscription_transfered',
        'Subscription Transferred',
        'Created when admin marks a subscription as transferred.',
        'Subscription Transferred',
        'Hello {full_name}, your subscription status has been marked as transferred.',
        'app://subscription/status',
    ),
    (
        'subscription_closed',
        'Subscription Closed',
        'Created when admin closes a subscription request.',
        'Subscription Closed',
        'Hello {full_name}, your subscription request has been closed.',
        'app://subscription/status',
    ),
    (
        'profile_completed',
        'Profile Completed',
        'Created when admin saves the full profile from the physical form.',
        'Profile Completed',
        'Hello {full_name}, your membership profile has been completed by the office.',
        'app://profile',
    ),
    (
        'physical_form_uploaded',
        'Physical Form Uploaded',
        'Created when the physical membership form photocopy is attached.',
        'Membership Form Attached',
        'Hello {full_name}, your physical membership form copy has been attached to your profile.',
        'app://profile/documents',
    ),
]


def seed_notification_events_and_rules(apps, schema_editor):
    NotificationEventMaster = apps.get_model('web', 'NotificationEventMaster')
    NotificationRule = apps.get_model('web', 'NotificationRule')

    for event_key, event_name, description, title_template, message_template, deep_link in EVENT_RULE_SEEDS:
        event, _ = NotificationEventMaster.objects.update_or_create(
            event_key=event_key,
            defaults={
                'event_name': event_name,
                'description': description,
                'is_active': True,
            },
        )
        NotificationRule.objects.get_or_create(
            event=event,
            defaults={
                'title_template': title_template,
                'message_template': message_template,
                'deep_link': deep_link,
                'send_immediately': True,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_add_subscription_status_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEventMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=80, unique=True)),
                ('event_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_event_master',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_template', models.CharField(max_length=180)),
                ('message_template', models.TextField()),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('send_immediately', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='web.notificationeventmaster')),
            ],
            options={
                'db_table': 'notification_rule',
                'ordering': ['event__id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='web.notificationrule')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='web.notificationeventmaster')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='web.userprofile')),
            ],
            options={
                'db_table': 'user_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'is_read'], name='user_notifi_user_pr_b349b3_idx'), models.Index(fields=['created_at'], name='user_notifi_created_0d33b6_idx')],
            },
        ),
        migrations.RunPython(seed_notification_events_and_rules, migrations.RunPython.noop),
    ]
