# Generated by Django 6.0.5 on 2026-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_add_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmasterplan',
            name='monthly_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionmasterplan',
            name='yearly_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
