# Generated by Django 6.0.5 on 2026-06-03 16:36

from django.db import migrations


def update_demo_user_plan(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SubscriptionMasterPlan = apps.get_model('web', 'SubscriptionMasterPlan')
    UserProfile = apps.get_model('web', 'UserProfile')

    user = User.objects.filter(username='demo_user').first()
    plan = SubscriptionMasterPlan.objects.filter(pk=5).first()

    if user and plan:
        UserProfile.objects.filter(user=user).update(subscription_plan=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_add_plan_rewards'),
    ]

    operations = [
        migrations.RunPython(update_demo_user_plan, migrations.RunPython.noop),
    ]
