# Generated by Django 6.0.5 on 2026-06-03 16:57

import django.db.models.deletion
import web.models
from django.db import migrations, models


def seed_payment_provider(apps, schema_editor):
    PaymentProvider = apps.get_model('web', 'PaymentProvider')
    PaymentProvider.objects.update_or_create(
        provider_key='razorpay',
        defaults={
            'provider_name': 'Razorpay',
            'mode': 'test',
            'is_active': True,
            'config': {
                'gateway': 'razorpay',
                'notes': 'Razorpay credentials are loaded from environment settings.',
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_update_demo_user_plan_to_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_key', models.CharField(max_length=50, unique=True)),
                ('provider_name', models.CharField(max_length=120)),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_provider',
                'ordering': ['provider_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('receipt', models.CharField(default=web.models.generate_payment_receipt, max_length=40, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('raw_gateway_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='web.subscriptionmasterplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='web.userprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='web.paymentprovider')),
            ],
            options={
                'db_table': 'payment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('bank', models.CharField(blank=True, max_length=80)),
                ('wallet', models.CharField(blank=True, max_length=80)),
                ('vpa', models.CharField(blank=True, max_length=120)),
                ('card_network', models.CharField(blank=True, max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gateway_status', models.CharField(blank=True, max_length=80)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_description', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='web.paymentorder')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='web.paymentprovider')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='web.userprofile')),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_refund_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('raw_gateway_response', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='web.paymentorder')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds', to='web.paymentprovider')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to='web.adminaccount')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='web.userprofile')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='web.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('event_name', models.CharField(max_length=120)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('is_valid_signature', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='web.paymentprovider')),
            ],
            options={
                'db_table': 'payment_webhook_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['user_profile', 'status'], name='payment_ord_user_pr_9a09cc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['created_at'], name='payment_ord_created_78bcca_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user_profile', 'status'], name='payment_tra_user_pr_2c1a34_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_order', 'status'], name='payment_tra_payment_56e752_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['user_profile', 'status'], name='payment_ref_user_pr_8c1c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment_order', 'status'], name='payment_ref_payment_e9090c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['event_name', 'is_processed'], name='payment_web_event_n_86bdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['received_at'], name='payment_web_receive_e0e451_idx'),
        ),
        migrations.RunPython(seed_payment_provider, migrations.RunPython.noop),
    ]
