# Generated by Django 6.0.5 on 2026-06-03 17:33

import django.db.models.deletion
from django.db import migrations, models


LOYALTY_EVENT_RULE_SEEDS = [
    (
        'loyalty_preference_selected',
        'Loyalty Preference Selected',
        'Created when a user selects monthly or yearly loyalty rewards.',
        'Loyalty Preference Saved',
        'Hello {full_name}, your {reward_frequency} loyalty reward preference is saved and locked until {locked_until}.',
        'app://loyalty',
    ),
    (
        'loyalty_reward_credited',
        'Loyalty Reward Credited',
        'Created when loyalty reward amount is credited to the user account.',
        'Loyalty Reward Credited',
        'Hello {full_name}, Rs. {reward_amount} has been credited for {reward_period}. Your loyalty balance is Rs. {loyalty_balance}.',
        'app://loyalty/history',
    ),
]


def seed_loyalty_notification_events(apps, schema_editor):
    NotificationEventMaster = apps.get_model('web', 'NotificationEventMaster')
    NotificationRule = apps.get_model('web', 'NotificationRule')

    for event_key, event_name, description, title_template, message_template, deep_link in LOYALTY_EVENT_RULE_SEEDS:
        event, _ = NotificationEventMaster.objects.update_or_create(
            event_key=event_key,
            defaults={
                'event_name': event_name,
                'description': description,
                'is_active': True,
            },
        )
        NotificationRule.objects.get_or_create(
            event=event,
            defaults={
                'title_template': title_template,
                'message_template': message_template,
                'deep_link': deep_link,
                'send_immediately': True,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_add_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_preference_locked_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_preference_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_reward_preference',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Monthly'), (1, 'Yearly')], null=True),
        ),
        migrations.CreateModel(
            name='UserLoyaltyAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_redeemed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_monthly_credit_at', models.DateTimeField(blank=True, null=True)),
                ('last_yearly_credit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='web.userprofile')),
            ],
            options={
                'db_table': 'user_loyalty_account',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRewardLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('adjustment', 'Adjustment')], default='credit', max_length=20)),
                ('reward_preference', models.SmallIntegerField(choices=[(0, 'Monthly'), (1, 'Yearly')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period_key', models.CharField(max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('mobile_app', 'Mobile App'), ('payment', 'Payment')], default='system', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_ledger_entries', to='web.subscriptionmasterplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger_entries', to='web.userprofile')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='web.userloyaltyaccount')),
            ],
            options={
                'db_table': 'loyalty_reward_ledger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile', 'created_at'], name='loyalty_rew_user_pr_f7ce1e_idx'), models.Index(fields=['period_key', 'entry_type'], name='loyalty_rew_period__444308_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_profile', 'reward_preference', 'period_key', 'entry_type'), name='unique_loyalty_reward_period')],
            },
        ),
        migrations.RunPython(seed_loyalty_notification_events, migrations.RunPython.noop),
    ]
