# Generated by Django 6.0.5 on 2026-06-03 17:45

import django.db.models.deletion
from django.db import migrations, models


def backfill_reward_points(apps, schema_editor):
    UserProfile = apps.get_model('web', 'UserProfile')
    RewardPoints = apps.get_model('web', 'RewardPoints')
    UserLoyaltyAccount = apps.get_model('web', 'UserLoyaltyAccount')

    account_balances = {
        account.user_profile_id: account.balance
        for account in UserLoyaltyAccount.objects.all()
    }

    for profile in UserProfile.objects.all():
        points, _ = RewardPoints.objects.get_or_create(
            user_profile=profile,
            defaults={
                'loyalty_reward': account_balances.get(profile.id, 0),
                'referral_rewards': 0,
                'global_pool_rewards': 0,
            },
        )
        if not profile.points_id:
            profile.points_id = points.id
            profile.save(update_fields=['points'])


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_add_loyalty_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loyalty_reward', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_rewards', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('global_pool_rewards', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to='web.userprofile')),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_points_owner', to='web.rewardpoints'),
        ),
        migrations.RunPython(backfill_reward_points, migrations.RunPython.noop),
    ]
