# Generated by Django 6.0.5 on 2026-06-07 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_add_reward_points_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='web.userprofile')),
            ],
            options={
                'db_table': 'issue_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueReportDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.issuereport')),
            ],
            options={
                'db_table': 'issue_report_documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['user_profile', 'status'], name='issue_repor_user_pr_627574_idx'),
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['report_id'], name='issue_repor_report__f80c63_idx'),
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['created_at'], name='issue_repor_created_e6ebf1_idx'),
        ),
    ]
