# Generated by Django 6.0.5 on 2026-06-11 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


PLAN_POOL_LIMITS = {
    'bronze': Decimal('2999.00'),
    'silver': Decimal('11999.00'),
    'platinum': Decimal('47999.00'),
    'gold': Decimal('191999.00'),
    'diamond': Decimal('767999.00'),
}


DIRECT_RULES = [
    (1, 5, Decimal('1.000')),
    (6, 10, Decimal('2.000')),
    (11, 15, Decimal('3.000')),
    (16, 20, Decimal('4.000')),
    (21, None, Decimal('5.000')),
]


INDIRECT_RULES = [
    (1, 'Consultant', [(1, 5, '0.500'), (6, 10, '1.000'), (11, 15, '1.500'), (16, 20, '2.000'), (21, None, '2.500')]),
    (2, 'Patron', [(1, 5, '0.500'), (6, 10, '1.000'), (11, 15, '1.500'), (16, 20, '2.000'), (21, None, '2.500')]),
    (3, 'Coach', [(1, 5, '0.250'), (6, 10, '0.500'), (11, 15, '0.750'), (16, 20, '1.000'), (21, None, '1.250')]),
    (4, 'Brand Ambassador', [(1, 5, '0.250'), (6, 10, '0.500'), (11, 15, '0.750'), (16, 20, '1.000'), (21, None, '1.250')]),
]


NOTIFICATION_RULES = [
    (
        'direct_referral_reward_credited',
        'Direct Referral Reward Credited',
        'Created when a direct referral reward is credited.',
        'Direct Referral Reward',
        'Hello {full_name}, Rs. {reward_amount} has been credited for your completed direct referral.',
        'app://rewards/history',
    ),
    (
        'indirect_referral_reward_credited',
        'Indirect Referral Reward Credited',
        'Created when an indirect referral reward is credited.',
        'Indirect Referral Reward',
        'Hello {full_name}, Rs. {reward_amount} has been credited from your {referral_role} referral level.',
        'app://rewards/history',
    ),
    (
        'global_pool_qualified',
        'Global Pool Qualified',
        'Created when a user completes two direct referrals and enters the global pool.',
        'Global Pool Qualified',
        'Hello {full_name}, you have qualified for the global pool with {referral_count} completed referrals.',
        'app://rewards/global-pool',
    ),
    (
        'global_pool_reward_credited',
        'Global Pool Reward Credited',
        'Created when a global pool distribution credits a user.',
        'Global Pool Reward',
        'Hello {full_name}, Rs. {reward_amount} has been credited from the global pool.',
        'app://rewards/history',
    ),
]


def generate_referral_code(existing_codes):
    code = f'SFC{uuid.uuid4().hex[:8].upper()}'
    while code in existing_codes:
        code = f'SFC{uuid.uuid4().hex[:8].upper()}'
    existing_codes.add(code)
    return code


def seed_reward_system(apps, schema_editor):
    UserProfile = apps.get_model('web', 'UserProfile')
    SubscriptionMasterPlan = apps.get_model('web', 'SubscriptionMasterPlan')
    GlobalPoolSetting = apps.get_model('web', 'GlobalPoolSetting')
    RewardRule = apps.get_model('web', 'RewardRule')
    NotificationEventMaster = apps.get_model('web', 'NotificationEventMaster')
    NotificationRule = apps.get_model('web', 'NotificationRule')

    existing_codes = set(
        UserProfile.objects.exclude(referral_code__isnull=True)
        .exclude(referral_code='')
        .values_list('referral_code', flat=True)
    )
    for profile in UserProfile.objects.filter(models.Q(referral_code__isnull=True) | models.Q(referral_code='')):
        profile.referral_code = generate_referral_code(existing_codes)
        profile.save(update_fields=['referral_code'])

    for plan in SubscriptionMasterPlan.objects.all():
        plan_name = (plan.plan_name or '').lower()
        for key, limit in PLAN_POOL_LIMITS.items():
            if key in plan_name:
                plan.global_pool_limit = limit
                plan.save(update_fields=['global_pool_limit'])
                break

    GlobalPoolSetting.objects.get_or_create(
        is_active=True,
        defaults={
            'membership_contribution_percentage': Decimal('10.000'),
            'business_net_profit_amount': Decimal('0.00'),
        },
    )

    for min_count, max_count, percentage in DIRECT_RULES:
        RewardRule.objects.get_or_create(
            reward_type='direct_referral',
            level=0,
            min_count=min_count,
            max_count=max_count,
            defaults={
                'role_name': 'Direct',
                'percentage': percentage,
                'is_active': True,
            },
        )

    for level, role_name, brackets in INDIRECT_RULES:
        for min_count, max_count, percentage in brackets:
            RewardRule.objects.get_or_create(
                reward_type='indirect_referral',
                level=level,
                min_count=min_count,
                max_count=max_count,
                defaults={
                    'role_name': role_name,
                    'percentage': Decimal(percentage),
                    'is_active': True,
                },
            )

    for event_key, event_name, description, title, message, deep_link in NOTIFICATION_RULES:
        event, _ = NotificationEventMaster.objects.update_or_create(
            event_key=event_key,
            defaults={
                'event_name': event_name,
                'description': description,
                'is_active': True,
            },
        )
        NotificationRule.objects.get_or_create(
            event=event,
            defaults={
                'title_template': title,
                'message_template': message,
                'deep_link': deep_link,
                'send_immediately': True,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_issuereport_issuereportdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPoolSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_contribution_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('business_net_profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'global_pool_settings',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionmasterplan',
            name='global_pool_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to='web.userprofile'),
        ),
        migrations.CreateModel(
            name='GlobalPoolEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('new_pool_member', 'New Pool Member'), ('recharge', 'Recharge'), ('upgrade', 'Upgrade')], max_length=30)),
                ('membership_reference', models.CharField(blank=True, max_length=120)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('membership_percentage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('membership_pool_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_net_profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_distribution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distributed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('undistributed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_global_pool_events', to='web.userprofile')),
            ],
            options={
                'db_table': 'global_pool_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalPoolDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calculated_share', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_credited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_limit_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_limit_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_pool_distributions', to='web.userprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='web.globalpoolevent')),
            ],
            options={
                'db_table': 'global_pool_distributions',
            },
        ),
        migrations.CreateModel(
            name='GlobalPoolMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qualified_at', models.DateTimeField()),
                ('qualified_by_direct_referrals_count', models.PositiveIntegerField(default=0)),
                ('max_pool_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pool_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('exited', 'Exited')], default='active', max_length=20)),
                ('last_reactivated_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_pool_members', to='web.subscriptionmasterplan')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_pool_member', to='web.userprofile')),
            ],
            options={
                'db_table': 'global_pool_members',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralClosure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depth', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_descendant_links', to='web.userprofile')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_ancestor_links', to='web.userprofile')),
            ],
            options={
                'db_table': 'referral_closure',
            },
        ),
        migrations.CreateModel(
            name='ReferralEdge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_membership_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_parent_edge', to='web.userprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_referrals', to='web.userprofile')),
            ],
            options={
                'db_table': 'referral_edges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardLedger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('loyalty', 'Loyalty'), ('direct_referral', 'Direct Referral'), ('indirect_referral', 'Indirect Referral'), ('global_pool', 'Global Pool')], max_length=30)),
                ('reward_subtype', models.CharField(blank=True, max_length=80)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('percentage_used', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credited_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('credited', 'Credited'), ('skipped', 'Skipped'), ('reversed', 'Reversed')], default='credited', max_length=20)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_reward_ledger_entries', to='web.userprofile')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_ledger_entries', to='web.subscriptionmasterplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger_entries', to='web.userprofile')),
            ],
            options={
                'db_table': 'reward_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reward_type', models.CharField(choices=[('direct_referral', 'Direct Referral'), ('indirect_referral', 'Indirect Referral')], max_length=30)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('role_name', models.CharField(blank=True, max_length=80)),
                ('min_count', models.PositiveIntegerField()),
                ('max_count', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reward_rules',
                'ordering': ['reward_type', 'level', 'min_count'],
                'indexes': [models.Index(fields=['reward_type', 'level', 'min_count', 'max_count'], name='reward_rule_reward__5327d9_idx')],
            },
        ),
        migrations.RunPython(seed_reward_system, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
        migrations.AddIndex(
            model_name='globalpoolevent',
            index=models.Index(fields=['trigger_type', 'created_at'], name='global_pool_trigger_f7e535_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpoolevent',
            index=models.Index(fields=['membership_reference'], name='global_pool_members_95739f_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpooldistribution',
            index=models.Index(fields=['receiver', 'created_at'], name='global_pool_receive_586ce4_idx'),
        ),
        migrations.AddConstraint(
            model_name='globalpooldistribution',
            constraint=models.UniqueConstraint(fields=('event', 'receiver'), name='unique_global_pool_event_receiver'),
        ),
        migrations.AddIndex(
            model_name='globalpoolmember',
            index=models.Index(fields=['status', 'updated_at'], name='global_pool_status_cd789b_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclosure',
            index=models.Index(fields=['ancestor', 'depth'], name='referral_cl_ancesto_f64101_idx'),
        ),
        migrations.AddIndex(
            model_name='referralclosure',
            index=models.Index(fields=['descendant', 'depth'], name='referral_cl_descend_4f0744_idx'),
        ),
        migrations.AddConstraint(
            model_name='referralclosure',
            constraint=models.UniqueConstraint(fields=('ancestor', 'descendant'), name='unique_referral_closure_pair'),
        ),
        migrations.AddIndex(
            model_name='referraledge',
            index=models.Index(fields=['parent', 'status'], name='referral_ed_parent__ef24da_idx'),
        ),
        migrations.AddIndex(
            model_name='referraledge',
            index=models.Index(fields=['child', 'status'], name='referral_ed_child_i_e0ba84_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['user_profile', 'reward_type', 'created_at'], name='reward_ledg_user_pr_3a1531_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardledger',
            index=models.Index(fields=['reference_id'], name='reward_ledg_referen_a4bae4_idx'),
        ),
    ]
