from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('membership/', views.membership, name='membership'),
    path('membership/checkout/', views.plan_checkout, name='plan_checkout'),
    path('dashboard/login/', views.DashboardLoginView.as_view(), name='dashboard_login'),
    path('dashboard/logout/', views.DashboardLogoutView.as_view(), name='dashboard_logout'),
    path('dashboard/home/', views.DashboardHomeView.as_view(), name='dashboard_home'),
    path('dashboard/profile/', views.UserProfileView.as_view(), name='dashboard_profile'),
    path('dashboard/subscription/', views.UserSubscriptionView.as_view(), name='dashboard_subscription'),
    path('api/mobile/signup/', views.MobileSignupAPIView.as_view(), name='mobile_signup'),
    path('api/mobile/login/', views.MobileLoginAPIView.as_view(), name='mobile_login'),
    path('api/mobile/change-password/', views.MobilePasswordChangeAPIView.as_view(), name='mobile_change_password'),
    path('api/mobile/report-issue/', views.MobileIssueReportAPIView.as_view(), name='mobile_report_issue'),
    path('api/mobile/report-issue/<str:report_id>/documents/', views.MobileIssueReportDocumentAPIView.as_view(), name='mobile_report_issue_documents'),
    path('api/mobile/notifications/', views.MobileNotificationListAPIView.as_view(), name='mobile_notifications'),
    path('api/mobile/notifications/<int:notification_id>/read/', views.MobileNotificationReadAPIView.as_view(), name='mobile_notification_read'),
    path('api/mobile/notifications/read-all/', views.MobileNotificationReadAllAPIView.as_view(), name='mobile_notifications_read_all'),
    path('api/mobile/loyalty/preference/', views.MobileLoyaltyPreferenceAPIView.as_view(), name='mobile_loyalty_preference'),
    path('api/mobile/loyalty/history/', views.MobileLoyaltyHistoryAPIView.as_view(), name='mobile_loyalty_history'),
    path('api/mobile/rewards/summary/', views.MobileRewardSummaryAPIView.as_view(), name='mobile_rewards_summary'),
    path('api/mobile/payments/create-order/', views.MobilePaymentOrderCreateAPIView.as_view(), name='mobile_payment_create_order'),
    path('api/mobile/payments/confirm/', views.MobilePaymentConfirmAPIView.as_view(), name='mobile_payment_confirm'),
    path('api/mobile/payments/history/', views.MobilePaymentHistoryAPIView.as_view(), name='mobile_payment_history'),
    path('api/payment/razorpay/webhook/', views.RazorpayWebhookAPIView.as_view(), name='razorpay_webhook'),
    path('club-admin/login/', views.admin_dashboard_login, name='admin_dashboard_login'),
    path('club-admin/logout/', views.admin_dashboard_logout, name='admin_dashboard_logout'),
    path('club-admin/dashboard/', views.admin_dashboard_home, name='admin_dashboard_home'),
    path('club-admin/users/', views.admin_registered_users, name='admin_registered_users'),
    path('club-admin/users/<str:profile_id>/', views.admin_user_details, name='admin_user_details'),
    path('club-admin/membership/', views.admin_membership_dashboard, name='admin_membership_dashboard'),
    path('club-admin/membership/plans/', views.admin_subscription_plans, name='admin_subscription_plans'),
    path('club-admin/membership/plans/<int:plan_id>/edit/', views.admin_subscription_plans, name='admin_subscription_plan_edit'),
    path('club-admin/payments/', views.admin_payments_dashboard, name='admin_payments_dashboard'),
    path('club-admin/loyalty-rewards/', views.admin_loyalty_rewards_dashboard, name='admin_loyalty_rewards_dashboard'),
    path('club-admin/membership/requests/', views.admin_membership_requests, name='admin_membership_requests'),
    path('club-admin/membership/requests/<str:request_id>/', views.admin_membership_request_details, name='admin_membership_request_details'),
    path('club-admin/notifications/send/', views.admin_send_notification, name='admin_send_notification'),
    path('club-admin/notifications/rules/', views.admin_notification_rules, name='admin_notification_rules'),
    path('club-admin/notifications/rules/<str:event_key>/', views.admin_notification_rule_detail, name='admin_notification_rule_detail'),
    path('club-admin/support/tickets/', views.admin_support_tickets, name='admin_support_tickets'),
    path('club-admin/support/tickets/<str:ticket_id>/', views.admin_ticket_details, name='admin_ticket_details'),
]
